-- WEEK 1 Day 3 — users 직원 마스터 확장 컬럼
-- users.phone 은 이미 있으면 IF NOT EXISTS 로 스킵

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS emp_name VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS department VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS position VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS phone VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS hire_date DATE NULL,
  ADD COLUMN IF NOT EXISTS memo VARCHAR(200) NULL;
