-- DB-60: 백오피스 v1.0 DDL(25 표) — 🔴 본사 전용 — ERP 에서는 no-op (2026-10-06 작8 갈래 라)
--
-- [왜 비웠나] 원래 본문은 본사 백오피스(hitpan_backoffice) 전용 25개 표 DDL 인데, ERP 마이그
--   러너가 이 폴더 전부를 돌린다(MigrationRunner.cs:64-74). 시드 두 행이 없는 옛 고객 DB 에서는
--   ERP tenants(varchar(36))가 IF NOT EXISTS 로 살아남은 채 tenant_business_info 가 BINARY(16)
--   FK 로 그걸 참조해 errno 150 으로 실패 → 러너가 여기서 return → DB-70~137(봉합 전부)이
--   영영 미적용이었다(선행검증 docs/검증/선행/20261006_선행검증서_DB39_60_옛DB생성_대조실측.md §3-3).
--
-- [결재] 작업지시서 docs/운영기록/20261006작8_백오피스_0사이클_데이터사슬봉합_작업지시서.md
--   §7-1(1안 ⓑ) · §7-6 CTO 조건부 승인(1회성 예외 — 선례 일반화 금지) · §7-7 사장님 전결(10/6).
--   파일·이름·번호는 보존한다(#37·#41). 백오피스 DDL 진실원은 installer/backoffice/*.sql +
--   SchemaMigrator — 이 파일은 백오피스 구축 경로가 아니다.
--
-- 🔴 ⓖ6 전제: 이 파일은 success=1 기록만으로 skip 된다 — 러너에 내용 비교를 추가하면 이 예외가 깨진다.
--   (러너는 checksum 을 기록만 하고 비교하지 않는다 — MigrationRunner.cs:130,139 실측.)
--
-- 원본 전문은 git 이력에 있다.
SELECT 1;
