# 20260825작1 — 업체·상품 (안전재고 경고·자동사슬·BOM 단계/생산가능)

| 항목 | 내용 |
|---|---|
| 문서번호 | 20260825작1 |
| 작성 | 설계팀장 존 |
| 작성일 | 2026-08-25 |
| 결재 | PM (SOP [2]) |
| 상태 | 🟢 **사장님 결재 완료 (8/25) — 전 항목 착수 가능** |
| 🔴 대원칙 | **"워크플로우 흐름에 데이터 정합성, 무결성이 깨지지 않는 원칙으로"** (사장님 8/25) |
| 선행 | [20260821작1](20260821작1_업체마스터3건_자동발주멱등_기본창고_작업지시서.md) · [설계2 업체특별단가](../설계/erp/20260820_설계2_업체특별단가_판매미연결_설계.md) |

---

## [1] 사장님 오더 (2026-08-25, 원문)

> **업체관리**
> 1. 업체특별단가 : **잘 작동하는지 조사!!**
>
> **상품관리 — 상품마스터**
> 1) 상단 안전재고 미달경고메시지 : **자동발주 실행해도 안없어짐**
>
> **BOM 자재명세서**
> 1) 상품마스터와 마찬가지로 **자재부족알림 발주해도 안없어짐**
> 2) BOM 그리드에 **버전 의미가 반제품→반반제품→…→완제품과 같은 상품의 버전 아님?**
>    볼트너트(1차반제품)-볼트너트오링(완제품)인데 **V1로 나옴**
> 3) BOM그리드에 **반제품 혹은 자재의 수량에 맞춰 생산가능 수가 나와야 함**

### 착수 전 결재 (AskUserQuestion 2회)

> **Q1. 경고는 언제 사라져야 합니까?**
> **A. 발주하면 사라지되 —**
>   1. **자동발주만** 된 품목 → *"재고부족품목 000외 0건이 자동발주 되었습니다. 매입처리 하셔야 재고에 반영됩니다. 매입처리 하시겠습니까?"* → **매입처리 될 때까지** 뜬다
>   2. **자동 사슬** 처리 항목 → *"재고부족품목 000외 0건 매입처리까지 완료되어 재고에 반영되었습니다."* → **30분간** 뜬다
>
> **Q2. BOM 「버전」 칸** → **A. 「단계」 칸을 새로 만든다**
>
> **Q3. 함께 손볼 것** → **A. 생산가능 수량 · 유령경고 정리 · 회귀 게이트 · 더블클릭 중복 차단(발주·매입확정 둘 다)**
>
> **Q4. 더블클릭 차단 수준** → **A. 버튼 + 서버 둘 다**

### 🔴 실측이 PM 판단을 2회 교정했다 — 기록

| | PM 초판 | 사장님 실측 | 확정 |
|---|---|---|---|
| 자동사슬 | *"껍데기다. 사슬을 새로 만들어야 하니 규모가 크다"* | *"실측했어. 자동사슬 하면 반영되"* → *"아니구나 자동사슬 반영 안되고 발주까지 가네"* | **화면마다 다르다** (§3-B) |

PM 이 **화면 안내문 글자**(`Items.razor:227` *"지금은 발주서만 생성됨"*)를 근거로 *"사슬 자체가 없다"* 고 단정했다.
**틀렸다.** 사슬은 `SalesService.cs:1774-1793` 에 **이미 있고 4/28 사고로 한 번 봉합까지 된 코드**다.
⇒ 이번 작업은 *"사슬을 만드는 일"* 이 아니라 **"있는 사슬을 두 화면에 잇는 일"** 이다. **규모가 작아졌다.**

🔴 **교훈: 주석·안내문은 코드가 아니다.** 8/21 주석 *"BOM 경로는 이미 정상"* 도 같은 방식으로 틀렸다(§3-A).
   두 번 다 **글자를 읽고 동작을 안 봤다.** [[feedback_gate_must_test_behavior]] 와 같은 계통이다.

---

## [2] 업체특별단가 조사 결과 — 🟢 **잘 작동한다. 이번 수정 대상 아님**

사장님 지시는 *"조사"* 였다. **결론: 죽은 기능이 아니다.**

| 축 | 판정 | 근거 |
|---|---|---|
| CRUD 종단 | 🟢 정상 | 라우트 4종 문자열 일치 (`SpecialPriceService.cs:23/39/54` ↔ `PartnerController.cs:227/246/298`) |
| **실제 사용처** | 🟢 **정상 — 6화면 전부 배선** | 발주 `PurchaseOrderGrid:34` · 매입 `PurchaseReceiptGrid:33` · 반품 `PurchaseReturnGrid:52` · 견적 `QuotationGrid:50` · 수주 `SalesOrderGrid:33` · 판매 `DeliveryGrid:38` |
| 자동 적용 | 🟢 정상 | `DeliveryGrid:85-92` — 표준단가로 채운 뒤 **업체특별단가 있으면 덮어씀** (8/20 사장님 C안 그대로) |
| 우선순위 | 🟢 정상 | 업체특별단가 > 상품기본단가. 상품특별단가는 **표시 전용**(게이트 G-53 이 정규식으로 자동적용 금지) |
| 테넌트 격리 | 🟢 정상 | 전 엔드포인트 `HttpContext.Items["TenantId"]` 만. 파라미터 수신 0건 (#2 준수) |
| 금액 타입 | 🟢 정상 | 전 계층 `decimal`. float/double 0건 (#4 준수) |

🟢 8/20 설계 §4-5 의 **6화면 완주가 실제로 확인됐다.** 회귀 게이트(G-49·51·52·55)도 살아 있다.

### ⚠️ 곁에서 나온 결함 3건 — **이번에 안 고친다. 별건 보고**

| | 결함 | 근거 | 왜 지금 안 고치나 |
|---|---|---|---|
| ㉮ | **유효기간이 무늬만** — `start_date`/`end_date` 조회 3곳 전부 필터 없음(`PartnerService.cs:83·609·832`), 저장은 `NULL` 하드코딩(`:125`), DTO·UI 에 칸 자체가 없음 | `CURDATE()` 비교 0건 | 값이 **전부 NULL** 이라 지금은 사고가 안 난다. **기간 기능 자체가 미구현** — 필요하신지 §8 ㄷ 로 여쭘 |
| ㉯ | **출하 DDL 만 제약이 다르다** — clean `UNIQUE(partner_id,item_id)` (`hitpan_db_clean.sql:2607`) vs 마이그 `UNIQUE(tenant_id,partner_id,item_id)` (`DB-11:45`) | 두 파일 실측 | 신규ID 는 UUID(`PartnerService.cs:101`)라 충돌 확률 0. **레거시 마이그로 코드성 ID 가 들어올 때만** 현실화 |
| ㉰ | 호출자 0건인 저장 경로 `master-special-prices` 3종 (`PartnerController.cs:146/160/174`) | Web 전체 grep 0건 | **지우지 않는다**(#1·#37). 보고만 |

🔴 ㉯ 는 [[project_multi_business_per_pc]](한 PC 5사업장 허용)와 맞물려 **이론이 아니다.** 마이그 트랙 착수 전 필독.

---

## [3] 상품·BOM — 무엇이 왜 터졌나

### 3-A. 🔴 경고가 발주해도 안 사라진다 — **원인은 "재고가 안 늘어서"가 아니다**

**PM 초기 추정(틀림)**: *"발주해도 입고 전엔 재고가 그대로니 경고가 남는 건 설계상 당연"*
**실제**: 발주하면 알림은 `pending → ordered` 로 **정상 전환된다**(`BomService.cs:975`). 배너는 `pending` 만 읽는다(`:868`).
   ⇒ **원래대로면 사라져야 한다.**

**진짜 원인 — 경고를 되살리는 코드가 있다.**

`GetAlertsAsync` 는 조회 **전에** 미달 품목을 `pending` 으로 INSERT 한다(`BomService.cs:825-856`).
그 중복 가드가 **`status='pending'` 만 본다**(`:849-854`):

```
1. 발주    → alert A: pending → ordered           (:975)
2. 화면 갱신 → GetAlertsAsync 재호출               (Items.razor:234 / Bom.razor:407)
3. INSERT 가드가 pending 만 찾음 → A(ordered)는 안 걸림 → 가드 통과
4. 재고는 아직 그대로 → 조건 만족 → 같은 품목에 새 pending B 가 INSERT
5. 배너가 그대로 다시 뜬다   ← 사장님이 보신 증상
```

🔴 **갱신하는 그 행위가 경고를 되살린다.** 누를수록 유령 행이 쌓인다(무한 증식).
🔴 **UI 버그가 아니다** — `StateHasChanged()` 는 정상 호출된다(`Items.razor:187·234·239`).
🔴 같은 가드 결함이 `SyncEventPublisher.cs:173-185` 에도 있다. **두 곳 다 고친다.**

🟢 **두 화면이 같은 API 를 쓴다** — `Items.razor:182` 와 `Bom.razor:221` 이 둘 다 `GET api/bom/alerts`.
   ⇒ **서버 한 곳을 고치면 두 화면이 동시에 고쳐진다.** (배너 UI 문구는 각자 인라인이라 따로)

#### 이것은 8/21 봉합의 **미봉합 구간**이다

`SalesService.cs:1648` 주석이 이렇게 단정했다:
> *"BOM 경로(BomService.OrderAlertAsync)는 stock_alerts.status 로 이미 정상 동작 — 판매 경로만 비어 있었다."*

**틀렸다.** `OrderAlertAsync` 는 정상이지만 **`GetAlertsAsync` 의 재삽입이 그걸 무효로 만든다.**
⇒ 판매 경로만 고치고 BOM/상품 경로는 안 고친 자리. 🔴 **[[project_fixed_vs_delivered_gap]] 5차 재발.**
🔴 **회귀 게이트가 0건**이라 아무도 못 잡았다 (`src/HitPan.Tests` 에 자동발주·안전재고 커버리지 **0건** — 실측).

#### ⚠️ 부수 함정 — 고쳐도 새는 자리

`OrderAlertAsync` 가 만드는 PO 는 **`status='draft'`**(`BomService.cs:941`).
`ReportService.cs:701` 의 발주중 집계는 `('ordered','partial')` 만 센다 ⇒ **draft 를 빠뜨리면 그대로 샌다.**
🔴 `SalesService.cs:1664` 는 `'draft'` 를 **포함**시켜 이 함정을 피했다. **그 정본을 따른다.**

---

### 3-B. 🔴 「자동 사슬」이 화면마다 다르다 — 사장님 실측 2회가 정확했다

| 어디서 누르나 | 지금 실제 | 근거 |
|---|---|---|
| **판매(거래명세서) 확정 후** 자동발주 | 🟢 **진짜 사슬** — 발주→매입전환→매입확정, **재고 반영됨** | `SalesService.cs:1774-1793` (`ConvertOrderToReceiptAsync` → `ConfirmReceiptAsync`) |
| **상품마스터** 배너 「자동 사슬」 | 🔴 **발주까지만** | `Items.razor:218-222` — 어느 쪽을 골라도 `OrderAlertAsync` 하나만 부름. `autoChain` 은 **글자에만** 쓰임(`:215·227`) |
| **BOM** 자재부족 「발주」 | 🔴 **발주까지만** — 사슬 선택지 자체가 없음 | `Bom.razor:402-409` |

🔴 **사슬을 새로 만들지 않는다.** 이미 있고 **4/28 사고로 봉합까지 된 검증된 코드**다
   (`SalesService.cs:1786-1792` — 실패 시 `Success=false` + 로그.
   주석 원문: *"이전 버그: Success=true 유지 → 사용자는 성공이라 알지만 stock_ledger INSERT 안 됨 → 재고부족 안 사라짐"*).

🟢 **품목별 스위치도 이미 있다** — `ItemDetail.razor:92` 「자동 매입확정」(`items.auto_receive_on_order`).
   `BomDtos.cs:124` 주석이 판정 규칙까지 명시: *"부족 자재 모두 Y면 자동 사슬, 하나라도 N이면 반자동."*

⇒ **할 일: 두 화면이 그 스위치를 읽고, 있는 사슬을 부르게 잇는다.**

🟢 **감사추적 안전** — `ItemDetail.razor:91` 주석: *"어느 쪽이든 발주서·매입명세서·원장은 동일하게 발자국 남음(#20)."*
   사슬을 써도 발주서·매입명세서가 **생략되지 않는다.** #3(원장 INSERT ONLY)·#6(confirmed 시점 반영) 위반 없음.

---

### 3-C. BOM 「버전」 — **버그가 아니다. 사장님이 원하시는 개념이 없는 것이다**

`bom_version` 은 **BOM 문서 개정 회차**다. `hitpan_db_clean.sql:646` `int DEFAULT 1`,
채번은 `MAX(bom_version)+1` **완성품(product_item_id) 별**(`BomService.cs:174-176·191`).

🔴 **볼트너트와 볼트너트오링은 서로 다른 완성품**이므로 각각 최초 등록이면 **둘 다 필연적으로 v1**.
   ⇒ **정상 동작이다.** 제조 단계가 몇 단이든 이 숫자는 안 변한다.

⚠️ 게다가 리비전으로서도 반쪽이다 — `UpdateAsync`(`:228-264`)가 **bom_version 을 안 올린다.** 내용을 고쳐도 v1 그대로.

**사장님이 원하시는 「단계」는 스키마에 없다**: `level`/`depth` 컬럼 0건 (DDL 실측).
🟢 그런데 **재료는 있다** — 반제품이 다른 BOM 의 자재가 되는 다단 연결은 이미 지원(`BomDetail.razor:278` 사장님 4/26 지시).
   `HasChildBom` 도 이미 계산된다(`BomService.cs:96-101`) — 다만 **소비처 0곳**이라 버려지고 있다(`BomModels.cs` 에 필드 없음).
⇒ **DB 변경 없이 계산으로 도출 가능.**

⚠️ 단 **실행은 여전히 1단계뿐**이다 — `CheckAssembleAsync`(`:342-385`)는 반제품이 부족하면 하위 BOM 으로 안 내려가고 반려한다
   (`Bom.razor:277-286`). 🔴 **이번에 그 헌법은 안 건드린다.** 단계는 **표시만** 한다.

---

### 3-D. BOM 「생산가능 수량」 — 없다. 그러나 **쉽다**

전 코드베이스 `생산가능|producible|MaxProduce` **0건**. 개념 자체가 없다.
가장 가까운 `CheckAssembleAsync` 는 방향이 반대 — *"N개 만들 수 있나"* (Yes/No) 만 답한다(`:377-384`).

🟢 **상세 API 에는 재료가 완비돼 있다**:
- 단위소요량 `bi.qty*(1+loss_rate/100) AS ActualQty` (`BomService.cs:85`)
- 현재고 `COALESCE(s.current_qty,0) AS CurrentStock` (`:88`, `item_stock` JOIN `:104`)

🔴 **목록 API 에는 없다** — `GetListAsync`(`:26-49`)에 `item_stock` JOIN 자체가 없고, 소요량은 GROUP BY 로 뭉개진다.
⇒ **목록 SQL 에 재고 조인 1개 + 집계식 1개.** 신규 테이블·컬럼·엔드포인트 **전부 불필요.**

⚠️ **창고 다중 함정**: `item_stock` 은 `warehouse_id` 포함 복합키(`hitpan_db_clean.sql:1795`).
   단순 JOIN 하면 창고 여럿일 때 **중복 집계**된다. 🔴 `BomService.cs:1163-1166` 이 쓰는
   `SELECT tenant_id,item_id,SUM(current_qty) GROUP BY` **서브쿼리 방식을 그대로 재사용한다.**

---

## [4] 작업 범위 — W1~W7

### W1. 🔴 경고 재삽입 차단 (P0 · 소)

| 파일 | 무엇 |
|---|---|
| `src/HitPan.Application/Services/BomService.cs:849-854` | INSERT 가드를 `sa.status IN ('pending','ordered')` 로 확대 |
| `src/HitPan.Infrastructure/Events/SyncEventPublisher.cs:173-185` | 동일 가드 확대 (같은 결함) |

🔴 **`ordered` 를 가드에 넣는 것이 핵심.** 이것만으로 사장님 증상이 멈춘다.
⚠️ `dismissed` 는 **넣지 않는다** — 사용자가 닫은 뒤 다시 미달이면 알려야 한다.

### W2. 🔴 자동 사슬 두 화면 연결 (P0 · **중~대**) — **사장님 Q1 답변의 뼈대**

> 🔴🔴 **초판 정정 (독립 반증 2026-08-25).** 초판은 이 항목을 *"인자 하나 추가 + 호출 두 줄, 규모 소~중"* 으로 적었다.
> **틀렸다.** 반증 결과 **①트랜잭션 재구성 ②DI 시그니처 변경 ③반제품 정책(P0·결재) ④`is_auto` 정책** 이 포함된다.
> ⇒ **W2 는 "사슬 연결"이 아니라 "`OrderAlertAsync` 재구성"이다.** 규모를 **중~대**로 올린다.

#### 🟢 W2-0. **사장님 결재 완료 (2026-08-25)** — 착수 차단 해제

> 🔴 **대원칙 (사장님 2026-08-25)**:
> ### **"워크플로우 흐름에 데이터 정합성, 무결성이 깨지지 않는 원칙으로"**
> ⇒ 이번 작업 **전체의 판단 기준**이다. 편의·간결함과 부딪히면 **정합성이 이긴다.**

| | 질문 | 🟢 사장님 결재 |
|---|---|---|
| **ㄹ** | 반제품에 사슬을 태울까 | 🔴 **"데이터 정합성이 중요하지 막아!!"** ⇒ **막는다** |
| **ㅁ** | 「자동」 표식을 붙일까 | 🟢 **"붙이고, 발주서가 자동생성되도록 하는 건 워크플로우 흐름의 정합성에 가장 잘 맞을 것 같은데?"** ⇒ **표식 붙이고 + 목록에도 보인다** |
| ㅁ-2 | 판매 자동발주서도 보일 텐데 | 🟢 **"둘 다 보인다 — 숨기는 조건을 없앤다"** |
| ㅁ-3 | 어떻게 구분하나 | 🟢 **"자동생성된 발주서 비고에 「자동발주서」 라고 표식"** |

🟢 **사장님 판단이 워크플로우상 정확하다** — 발주서가 목록에 뜨면
**발주(3단계) → 매입전환 → 매입확정 → 재고 반영** 이라는 6단계 흐름(#8)을 그대로 탄다.
`PurchaseOrderPage.razor:64` 에 **「매입전환」 버튼이 이미 있다.**
지금은 자동발주서만 그 흐름 **밖으로 빠져 있었다.**

---

#### 🔴 W2-0-A. 반제품 차단 (사장님 ㄹ 결재)

**막는다.** 사슬뿐 아니라 **자동발주 자체를 어디까지 막을지**가 갈린다:

| 층 | 무엇 | 판단 |
|---|---|---|
| ① **사슬(매입확정)** | 반제품이면 **태우지 않는다** | 🔴 **필수** — 회계 오염 차단 |
| ② **발주서 생성** | 반제품이면 발주서도 안 만드나 | ⚠️ **막지 않는다** — 사장님은 *"사슬"* 을 막으라 하셨다. 발주서까지 막으면 외주 매입 길이 끊긴다(#20) |
| ③ **알림 자체** | 반제품 알림을 띄우나 | ⚠️ **띄운다** — 부족한 건 사실이다. 알려야 한다 |

⇒ **반제품은 「발주서만」 경로로 강제한다.** 스위치가 Y여도 사슬을 안 탄다.
🔴 **조용히 넘어가지 마라** — 화면에 이유를 보여준다:
   *"○○(반제품)은 매입확정까지 자동으로 하지 않습니다. 발주서만 만들었습니다."*
   (사유: 반제품은 만들어 채우는 것이라 사지 않은 물건이 재고·장부에 잡히면 안 된다)

**판정 기준**: `items.item_type` 이 `'semi_finished'` · `'finished'` · `'product'` 이면 사슬 제외.
   `'material'`(자재)만 사슬 허용. 🔴 **DESCRIBE 로 실제 enum 값 실측 후 확정**(#13).

⚠️ **판매 경로에도 같은 결함이 있다**(`SalesService.cs:1613-1665` 에 `item_type` 필터 0건).
   🔴 **같이 막는다** — 한쪽만 막으면 [[project_fixed_vs_delivered_gap]] 6차 재발이다.

---

#### 🔴 W2-0-B. `is_auto` 표식 + 목록 노출 (사장님 ㅁ 결재)

| # | 무엇 | 파일 |
|---|---|---|
| ① | BOM 자동발주 INSERT 에 **`is_auto` 컬럼 추가 → 값 1** | `BomService.cs:938-941` |
| ② | 🔴 **목록에서 숨기는 조건 삭제** — `AND po.is_auto = 0` 한 줄 제거 | `PurchaseService.cs:521` |
| ③ | 자동생성 발주서 **비고 = "자동발주서"** | 아래 표 |

**②의 이력 — 5/4에 개발팀이 자체 판단으로 넣은 줄이다**(커밋 `e09ff8bb`, 메시지 *"자동발주 목록 노출 차단"*).
🔴 **사장님 결재 문서가 없다**(전수 검색). ⇒ 사장님 지시가 우선한다.
🟢 **지우는 게 아니라 흐름을 복원하는 것**이다 — 지금까지 판매 자동발주서는 **아무도 모르게 쌓이고 있었다.**

**③ 비고 문구 — 🔴 지금 값이 고객에게 개발용어를 노출하고 있다**

| 경로 | 지금 (🔴 문제) | 바꿀 값 |
|---|---|---|
| BOM | `"BOM 자재부족 자동발주 (alert 3f2a8b1c)"` — 🔴 `alert` + **내부 식별자 노출** | **`"자동발주서 — BOM 자재부족"`** |
| 판매 | `"안전재고 자동발주 (판매확정 트리거)"` — 🔴 **「트리거」** | **`"자동발주서 — 안전재고 미달(판매확정)"`** |
| 상품마스터 | (BOM 과 같은 경로를 씀) | **`"자동발주서 — 안전재고 미달"`** |

🔴 **머리에 "자동발주서" 를 둔다** — 목록 비고 칸은 잘려 보이므로 **앞부분이 살아야** 한다.
🔴 [[feedback_no_dev_jargon_customer_facing]] — alert·트리거·식별자 전부 뺀다.

---

#### 🔴 W2-0-C. 결재의 근거가 된 실측 (반증 2026-08-25)

**(가) 반제품 — 왜 막아야 했나**

사슬 경로 전체(알림생성 SQL `BomService.cs:826-855` · `OrderAlertAsync:889-904` · `ConfirmReceiptAsync:184-460` · 판매경로 `SalesService.cs:1613-1665`)에 **`item_type` 검사가 0건**이다.
`RegisterBomAsItemAsync`(`:284-317`)가 같은 `items` 행의 타입만 `semi_finished` 로 바꾸므로,
**반제품에 안전재고·자동발주가 켜져 있으면 그대로 알림에 걸린다.**

사슬을 태우면 `ConfirmReceiptAsync` 가:
- `stock_ledger` IN + `item_stock` 증가
- 🔴 `AutoJournalHelper.RecordPurchaseConfirmAsync`(`:413`) **매입 분개**
- 🔴 `partner_balance.total_purchase` 가산(`:426-440`) — **있지도 않은 외상매입금**

⇒ **사지 않은 물건이 재고로 잡히고 갚을 돈이 생긴다.** 재고 오염보다 회계 오염이 더 무겁다.

🟢 **사장님 4/27 헌법과 일치한다** (`docs/개발/erp/next_session_prompt_20260428.md:23·26`):
> *"자재가 들어오기 전에 완제품이 +되는 일은 절대 없어야 함"*
> *"다단 반제품/완제품은 **자동발주 아닌 자동생산**"*

⚠️ 반제품을 외주가공으로 사 오는 길은 **발주서 경로로 살아 있다**(W2-0-A ②) — 흐름은 안 끊긴다(#20).
⚠️ 현재 유일한 방어는 `auto_order_partner_id` 없으면 예외(`:913-914`) — **우연에 가까웠다.**

**(나) `is_auto` — 왜 통일해야 했나**

| | INSERT 시 `is_auto` |
|---|---|
| 판매 경로 `SalesService.cs:1724-1726` | **1** |
| BOM 경로 `BomService.cs:938-941` | 🔴 **컬럼 자체가 없음 → 0** |

파급 2건 — 🔴 **둘 다 정합성 문제다**(사장님 대원칙):
1. `PurchaseService.GetOrdersAsync:521` 이 `AND po.is_auto = 0` ⇒ **판매 자동발주서가 목록에서 사라진다.**
   ⇒ **아무도 모르게 쌓인다.** 매입전환을 안 해 재고가 안 늘고, 그래서 또 자동발주가 나간다.
2. 판매 경로 멱등 필터(`SalesService.cs:1655-1665`)는 `po.is_auto=1` 을 요구 ⇒ **BOM 이 만든 발주를 못 본다.**
   BOM 에서 발주한 품목이 판매확정 때 **또 후보로 뜬다** — 중복 발주.

🟢 **W2-0-B 가 둘 다 닫는다** — 표식을 붙이면 ②가 닫히고, 숨김을 없애면 ①이 닫힌다.

#### W2-1. 🔴 트랜잭션 재구성 — **초판 지시가 그대로면 반드시 실패한다**

**초판**: *"`SalesService.cs:1774-1793` 패턴 그대로 재사용"* ← **문자 그대로 하면 안 돈다.**

| | 커넥션 | 사슬 호출 위치 |
|---|---|---|
| `SalesService` | Dapper `IDbConnection` | 🟢 **`tx.Commit()`(`:1757`) 뒤** — 트랜잭션 **밖** |
| `PurchaseService` | 🔴 **EF `AppDbContext`** (`_unitOfWork`) | — |
| `BomService.OrderAlertAsync` | Dapper `IDbConnection` | 🔴 `tx` 가 **메서드 끝(`:978`)까지 열려 있다** |

🔴 **`IDbConnection` 과 EF DbContext 는 물리적으로 다른 커넥션이다**
   (`InfrastructureExtensions.cs:60` DbContext / `:65` `new MySqlConnection` — 별개 인스턴스).

`tx` 안에서 `purSvc.ConvertOrderToReceiptAsync` 를 부르면:
1. EF(커넥션 A)가 조회 → BomService `tx`(커넥션 B)는 미커밋 ⇒ **PO 가 안 보인다** → *"발주서를 찾을 수 없습니다"*
2. 보였더라도 `ConfirmReceiptAsync:398-408` 의 `stock_alerts` UPDATE(A)가 B 가 잠근 같은 행을 건드려 **락 대기 → timeout**

⇒ 🔴 **`using var tx` 블록을 좁히고, `tx.Commit()` **뒤에** 별도 try/catch 에서 사슬을 부른다.**
   **판매 정본의 순서를 따른다: 커밋 → 감사로그 → 사슬** (`SalesService.cs:1757-1774`).
   **이것은 인자 추가가 아니라 메서드 본문 재구성이다.**

#### W2-2. 🔴 DI 시그니처 변경 — 초판이 놓쳤다

`BomService` 생성자는 **`IDbConnection`·`IEventPublisher`·`IAuditService` 3개뿐**(`BomService.cs:16`).
**`IServiceProvider` 가 없다.** 반면 `SalesService:28` 은 받고 있고 `:1778` 에서 `GetService<IPurchaseService>()` 한다.

- 🔴 **`IServiceProvider` 방식을 따른다.** `IPurchaseService` 를 생성자로 **직접 주입하지 마라** — 순환 의존 위험(판매 정본이 우회한 이유일 가능성).
- 🟢 `Program.cs:103` `AddScoped<IBomService, BomService>()` 는 **자동 해석** — 등록은 안 건드려도 된다.
- ⚠️ **`BomService` 생성자를 직접 부르는 시험 코드가 있으면 전부 깨진다** — 착수 전 grep 필수(#12).
- 🟢 `PurchaseService` 는 `IBomService` 를 참조하지 않는다(실측) — **순환 없음.**

#### W2-3. 배선 (초판 유지)

| 파일 | 무엇 |
|---|---|
| `BomDtos.cs` `StockAlertDto` | `AutoReceiveOnOrder` 추가 |
| `BomService.cs:860-872` `GetAlertsAsync` SELECT | `items.auto_receive_on_order` 조인 |
| `BomService.cs:883` `OrderAlertAsync` | `autoReceive` 인자 + **W2-1 재구성** |
| `BomController.cs:192` | `[FromQuery] bool autoReceive` |
| `Web/Services/BomService.cs:180` | 인자 전달 |
| `Items.razor:218-222` · `Bom.razor:402` | 품목 스위치 읽어 분기 |

🔴 **판정 규칙은 이미 정해져 있다**(`BomDtos.cs:124`): **부족 자재 모두 Y면 사슬, 하나라도 N이면 반자동.**
🔴 **실패 처리는 정본을 따른다** — 매입확정 실패 시 `Success=false` + 로그(#15). **조용히 성공으로 위장 금지.**
🔴 **새 사슬을 짜지 마라.** 기존 서비스를 호출한다. 복사해 만들면 4/28 봉합이 한쪽에만 남는다.

#### ⚠️ W2-4. 사슬이 조용히 끊기는 자리 2곳 — 가드 필요

| | 무엇 | 근거 |
|---|---|---|
| **단가 0원** | `ConfirmReceiptAsync:202-205` 가 `합계 <= 0` 이면 **예외**. `OrderAlertAsync:896` 단가는 `COALESCE(purchase_price, cost_price, 0)` ⇒ 둘 다 없으면 **0** ⇒ **발주만 남고 사슬이 끊긴다** | 🔴 사슬 진입 전 단가 0 자재를 걸러 **사용자에게 이유를 보여준다** |
| **월마감** | `ConfirmReceiptAsync:208` `EnsureNotClosedAsync` — 마감월이면 예외 | BOM 화면에 **새로 노출되는 실패 경로**. 안내문 필요 |

#### 🟢 W2-5. 반증으로 **안전이 확인된** 축 — 추가 작업 없음

| | 확인 |
|---|---|
| **draft PO 매입전환** | 🟢 `ConvertOrderToReceiptAsync:593-700` 에 **status 검사 0건.** 판매 정본도 `draft` PO(`SalesService:1726`)를 그대로 전환한다 — **이미 프로덕션에서 도는 경로** |
| **창고** | 🟢 발주에 `warehouse_id` 가 없어도(`BomService:957`) 폴백이 받는다 — 품목기본창고(`:662`, 8/21 W6) → 테넌트기본(`:674`) → 없으면 예외(`:677`, 유령창고 차단) |
| **원장 길이** | 🟢 매입확정은 `receipt.ReceiptId`(UUID 36자)를 쓴다(`:257`) — `stock_ledger.source_id varchar(36)` 초과 없음 (6/22 P0 재발 아님) |

### W3. 🔴 발주 후 안내 메시지 2종 (사장님 지시 원문 · 소)

| 경우 | 메시지 | 지속 |
|---|---|---|
| 자동발주만 | *"재고부족품목 {품목명}외 {N}건이 자동발주 되었습니다. **매입처리 하셔야 재고에 반영됩니다.** 매입처리 하시겠습니까?"* | 🔴 **매입처리 될 때까지** |
| 자동 사슬 | *"재고부족품목 {품목명}외 {N}건 **매입처리까지 완료되어 재고에 반영되었습니다.**"* | 🔴 **30분간** |

⚠️ **"매입처리 될 때까지"의 구현** — 스낵바(휘발)로는 못 한다. `stock_alerts.status='ordered'` 행을 읽어
   **배너 자리에 다른 색(파랑/정보)으로 상시 노출**한다. 「매입처리 하시겠습니까」 = 발주목록으로 가는 버튼.
   🟢 이러면 사장님 Q1 취지(*"경고는 사라지되 잊지 않게"*)가 그대로 산다.
   🟢 매입확정되면 `PurchaseService.cs:398-408` 이 이미 `received` 로 닫으므로 **자동으로 사라진다** — 새 코드 불필요.
⚠️ **"30분"의 기준시각** — `stock_alerts.updated_at`(사슬 완료 시각). 서버시각 기준.
🔴 **개발용어 금지** — 고객 노출 문구에 status·PO·alert 같은 말 금지 [[feedback_no_dev_jargon_customer_facing]].

### W4. 🔴 더블클릭 중복 차단 — 버튼 + 서버 둘 다 (사장님 Q4 · 소)

| 층 | 무엇 |
|---|---|
| 버튼 | `Items.razor:43` 는 `_orderingSafety` 로 이미 잠김 🟢 / 🔴 `Bom.razor` 발주 버튼은 **잠금 없음** → 추가 |
| 서버 (발주) | `OrderAlertAsync:910` 의 `Status != "pending"` throw 를 **트랜잭션 안 `SELECT ... FOR UPDATE`** 로 승격 — 동시요청도 막는다 |
| 서버 (매입확정) | 🟢 **이미 막힌다 — 근거 정정**(반증). 초판이 지목한 `:641` 은 가드가 아니라 **"전환할 라인 0건"일 때 안내문을 고르는 분기**다. **진짜 가드는 `:610-622`**(미확정 매입명세 있으면 전환 차단) **+ `:626`**(`OrderedQty-ReceivedQty>0` 라인만 추림) |

**2회차가 막히는 경로 (반증 실측)**: 1회차에 `ReceivedQty += Qty` → `ItemStatus='closed'`(`:289`) → PO `'received'`(`:375`)
⇒ 2회차엔 `:626` 필터에서 전량 소진 → `receiptItems.Count==0` → `:644` 예외. **멱등 확보됨.**
🟢 **최후 방어선이 하나 더 있다** — `stock_ledger` UNIQUE `(tenant, source_type, source_id, item_id, move_type)`(`PurchaseService:236` 주석). DB 가 막는다.

⚠️ **결정 필요**: 사슬 재호출 시 사용자에게 *"이미 매입이 완료된 발주서입니다"* 예외가 뜬다.
   이를 **정상(무시)로 처리할지 실패로 표시할지** — 구현 명세서에 근거 기록. 🔴 **조용히 삼키지 마라**(#15).

🔴 사장님 지시: *"상품마스터 자동발주·사슬 혹은 BOM 자동발주/사슬 더블클릭 해도 **중복발주, 혹은 중복매입확정까지 가지 않도록**"*
⇒ **매입확정 중복이 더 위험하다**(원장·분개·외상매입금에 두 번 쓴다). 발주 중복보다 **이쪽을 먼저 실증한다.**

### W5. BOM 「단계」 칸 (사장님 Q2 · 중)

| 파일 | 무엇 |
|---|---|
| `BomService.cs:26-49` `GetListAsync` | 단계 계산 (자재=1 · 1차 반제품=2 · … · 완제품=N) |
| `BomDtos.cs` `BomListDto` · `BomModels.cs` `BomListModel` | `BomLevel` 추가 |
| `Bom.razor:90·99` | 헤더 「버전」 → 「단계」 |

⚠️ **기존 `bom_version` 은 지우지 않는다**(#1·#37). 칸을 「개정」으로 이름만 바꿀지 숨길지는 **§8 ㄱ 사장님 판단.**
⚠️ **재귀 방식** — MariaDB 11.4.10 이라 `WITH RECURSIVE` 가용. 다만 테넌트당 BOM 행수가 적어 **C# 메모리 계산이 더 안전**할 수 있다. 구현자 판단 후 명세서에 근거 기록.
🔴 **순환참조 방어 필수** — `HasCircularRefRecursiveAsync`(`:993-1022`) 패턴 재사용. **무한루프로 화면이 멈추면 P0.**

### W6. BOM 「생산가능 수량」 칸 (사장님 지시 ③ · 소)

`GetListAsync` SQL 에 **창고합산 서브쿼리** 조인 + `MIN(FLOOR(재고 / NULLIF(소요량,0)))`.
- 🔴 창고합산은 `BomService.cs:1163-1166` 방식 재사용 (§3-D 함정)
- 🔴 자재 0개 BOM → `MIN` 이 NULL → `COALESCE(...,0)`
- DTO·Model·화면 각 1줄

### W7. 유령 경고 정리 + 회귀 게이트 (사장님 Q3 · 소)

| | 무엇 |
|---|---|
| 정리 | 마이그 SQL 1개 — 같은 `(tenant_id,item_id)` 에 `pending` 2건 이상이면 **최신 1건만 남기고 나머지 `dismissed`**. 🔴 **DELETE 하지 않는다**(기록 보존·#3 정신) |
| 게이트 | `StockAlertIdempotencyGateTests.cs` 신설 — ① INSERT 가드에 `'ordered'` ② `OrderAlertAsync` 사슬 분기 ③ 발주중 집계에 `'draft'` |

🔴 **게이트는 글자검사로 끝내지 마라** [[feedback_gate_must_test_behavior]] — 가짜 누적 9번.
   **봉합을 빼고 FAIL 이 나는지 먼저 확인**한 뒤 되돌린다. 반환값 판정 금지.
🔴 마이그 번호는 **최신 확인 후 채번** — 8/24 `DB-100` 충돌 사고 [[project_migration_id_collision_20260825]].

---

## [5] 헌법 점검

| 조항 | 점검 | 판정 |
|---|---|---|
| 🔴 **대원칙(8/25)** | **"워크플로우 흐름에 데이터 정합성·무결성이 깨지지 않는 원칙"** — 반제품 차단·표식 통일·목록 복원 **3건 모두 이 원칙의 적용** | 🟢 |
| #1 덮어쓰기 금지 | `bom_version`·특별단가 기간칸·죽은 엔드포인트 **전부 존치**. ⚠️ `is_auto=0` 필터 삭제는 **예외** — 사장님 결재로 흐름 복원 | 🟢 |
| #8 6단계 순서 | 🟢 자동발주서가 목록에 뜨면 **발주(3단계)→매입→재고** 흐름을 탄다. 종전엔 그 흐름 **밖**이었다 | 🟢 |
| #2 tenant_id JWT | 신규 파라미터 수신 0건. `autoReceive` 는 업무 플래그 | 🟢 |
| #3 원장 INSERT ONLY | 사슬은 기존 `ConfirmReceiptAsync` 재사용 — 원장 UPDATE 0 | 🟢 |
| #6 confirmed 시점 반영 | 사슬이 **매입확정을 실제로 거친다.** 재고 직접 조작 없음 | 🟢 |
| #13 DESCRIBE 의무 | 🔴 **착수 전 `stock_alerts`·`bom_headers`·`bom_items`·`item_stock`·`purchase_order_items` 실측 필수** | ⚠️ 착수조건 |
| #15 빈 catch 금지 | W2 실패 시 로그+Success=false. 🔴 기존 `Web/Services/BomService.cs:161·187` 빈 catch 도 **이번에 로그 추가** | 🟢 |
| #19 빌드 0/0 | 게이트 | ⚠️ 검증조건 |
| #20 흐름 안 끊김 | 사슬 써도 발주서·매입명세서 발자국 유지 | 🟢 |
| #25 쉽게 | 메시지가 다음 할 일을 알려준다(매입처리) | 🟢 |
| #36 출하 DDL | **DDL 변경 0건** — W1~W6 전부 로직. W7 정리 마이그만 추가 | 🟢 |
| #37 수신칸 제거 금지 | 기간칸·`master-special-prices` 존치 | 🟢 |
| 반자동 원칙 | 🔴 사슬은 **품목별 스위치가 Y일 때만.** 코드가 임의로 켜지 않는다 [[feedback_semi_auto_principle]] | 🟢 |

---

## [6] 검증 조건 (SOP [4] 데이비드 박)

🔴 **개발PC 정상은 검증이 아니다** [[feedback_dev_pc_proves_nothing]]. **대조실험**으로 실증한다.

| # | 무엇을 | 어떻게 (🔴 실측) |
|---|---|---|
| V1 | 경고가 실제로 사라지나 | 미달 품목 만들고 **발주 → 배너 사라짐**. 🔴 **W1 을 빼고 돌려 FAIL 재현부터** |
| V2 | 유령 행이 안 쌓이나 | 발주 후 화면 **10회 새로고침** → `stock_alerts` pending 증가 **0** |
| V3 | 사슬이 재고에 반영되나 | 스위치 **Y** 품목 → 사슬 → `item_stock.current_qty` 증가 + `stock_ledger` INSERT **1건** |
| V4 | 반자동은 안 넘어가나 | 스위치 **N** 품목 → **발주서만.** 재고 무변화 (**대조군**) |
| V5 | 🔴 더블클릭 | 발주 버튼 **연타 5회** → PO **1건**. 사슬 연타 → 매입확정 **1건**, `stock_ledger` **1건** |
| V6 | 메시지 2종 | 자동발주만 → 매입처리 안내 **상시** / 사슬 → 완료 메시지 **30분** / 매입확정하면 **자동 소멸** |
| V7 | BOM 단계 | 볼트너트=2 · 볼트너트오링=3 처럼 **실제 데이터로**. 🔴 **순환참조 BOM 넣어도 안 멈추는지** |
| V8 | 생산가능 수량 | 자재 재고 바꿔가며 **최솟값 자재가 결정하는지**. 🔴 **창고 2개로 나눠 넣어 중복집계 안 되는지** |
| V9 | 회귀 0 | 기존 시험 **659개 전부 통과** |
| V10 | 빌드 | errors 0 + warnings 0 |
| **V11** | 🔴 **트랜잭션** (W2-1) | 사슬 1회 태워 **"발주서를 찾을 수 없습니다"·락 timeout 이 안 나는지.** 🔴 **재구성 전 코드로 먼저 돌려 실패를 재현**한 뒤 고친다 — 안 그러면 "원래 됐던 것"과 구분이 안 된다 |
| **V12** | 🔴🔴 **반제품 차단** (W2-0-A) | 반제품에 자동발주·자동매입확정 **둘 다 켜고** 사슬 시도 → ① **매입확정 안 됨** ② 🔴 **`journal_lines` 신규 0건** ③ 🔴 **`partner_balance.total_purchase` 무변화** ④ **발주서는 만들어진다**(외주 길 유지) ⑤ **화면에 이유가 보인다**. 🔴 **자재(material) 대조군은 사슬이 정상 동작**해야 한다 |
| **V12-b** | 🔴 **판매 경로도 막혔나** | 반제품이 든 거래명세서 확정 → 자동발주 후보에 **반제품이 안 뜨거나 사슬을 안 탄다.** 한쪽만 막으면 미봉합 |
| **V13** | 단가 0원 (W2-4) | 매입단가·원가 둘 다 없는 자재 → 사슬 → **이유가 화면에 보이는지.** 조용한 실패 금지 |
| **V14** | 🔴 **`is_auto` + 목록 노출** (W2-0-B) | ① BOM 자동발주 PO 에 `is_auto=1` ② 🔴 **BOM·판매 자동발주서가 둘 다 발주서 목록에 뜬다** ③ **비고 앞머리가 「자동발주서」** ④ 목록에서 열어 **「매입전환」이 실제로 된다**(흐름 연결 실증) ⑤ 판매확정 시 **BOM 발주 품목이 후보에서 빠진다**(중복 차단) |
| **V15** | 🔴 **개발용어 0** | 비고·안내문에 `alert`·트리거·식별자·status **한 글자도 없는지** 눈으로 확인 |

---

## [7] 착수 조건

1. 🟢 **사장님 결재 완료** (8/25 — ㄹ·ㅁ). PM 결재 후 착수 (#33·#42)
2. 🔴 **DESCRIBE 실측** — `stock_alerts`·`bom_headers`·`bom_items`·`item_stock`·`purchase_order_items`
   🔴 **+ `items.item_type` enum 값 실측** (W2-0-A 판정 기준) (#13)
3. 🔴 **운영(demo) 수술 금지** (#39) — 검증은 테스트환경
4. 🔴 W2 는 **원장·분개·외상매입금에 쓰는 동작**이다. **V3·V4·V11·V12 대조실험 없이 완료 보고 금지**
5. 🔴 W2-2 착수 전 **`new BomService(` 전수 grep**(#12) — 생성자가 바뀌면 시험 코드가 깨진다

### 🟢 착수 순서 — 무거운 것을 뒤로

```
1순위  W1 (경고 재삽입 차단)   ← 사장님 증상이 바로 멎는다
2순위  W7 (유령 정리 + 게이트) ← W1 을 지킨다
3순위  W6 (생산가능 수량)      ← DB 변경 0, 독립적
4순위  W5 (BOM 단계)           ← §8 ㄱ 만 확인되면 됨
5순위  W2 (사슬 + 반제품차단 + is_auto)  ← 🔴 가장 무겁다. 원장·분개에 쓴다
6순위  W3·W4                   ← W2 결과 위에 얹힌다
```

⚠️ **W3(안내 메시지)은 W2 뒤에 온다** — 「자동발주만/사슬완료」 두 메시지가 **W2 의 분기 결과**를 읽기 때문이다.
⚠️ **W2 안에서도 순서가 있다**: W2-0-B(표식·목록) → W2-0-A(반제품 차단) → W2-1(트랜잭션) → W2-3(배선).
   🔴 **반제품 차단을 사슬 연결보다 먼저 넣는다** — 순서가 뒤집히면 **차단 없는 사슬이 잠깐이라도 도는 창**이 생긴다.

---

## [8] PM 이 판단 못 한 것 — 사장님께 여쭐 것

| # | 무엇 | 왜 PM 이 못 정하나 |
|---|---|---|
| ✅ **ㄹ** | ~~반제품에 자동 사슬을 태울 것인가~~ | 🟢 **결재 완료** — *"데이터 정합성이 중요하지 막아!!"* ⇒ W2-0-A |
| ✅ **ㅁ** | ~~「자동」 표식을 붙일 것인가~~ | 🟢 **결재 완료** — 붙이고 + 목록에도 보이게 + 비고에 「자동발주서」 ⇒ W2-0-B |
| ㄱ | 「버전」 칸을 **숨길지 「개정」으로 남길지** | 이미 v2·v3 을 쓰고 계신 고객이 있으면 숨기면 안 된다. **화면 보시고 판단하실 일** (W5 착수 시 여쭘 — 나머지는 막지 않는다) |
| ㄴ | 「30분」이 **맞는 길이인지** | 사장님이 주신 값. 써 보시고 짧거나 길면 조정 |
| ㄷ | 특별단가 **유효기간을 만들지** (§2 ㉮) | 지금 없어도 굴러간다. 필요하신지는 현장 판단 |

---

## [9] 🔴 독립 반증 기록 — **PM 판단이 3번 틀렸다**

작성 직후 독립 반증을 돌렸고(SOP [3-V] 정신), **초판의 낙관이 깨졌다.**

| # | PM 초판 | 반증 결과 |
|---|---|---|
| 1 | *"판매 패턴 그대로 재사용하면 된다"* | ❌ **문자 그대로 하면 반드시 실패.** 트랜잭션 구조가 다르다 (W2-1) |
| 2 | (DI 언급 없음) | ❌ `BomService` 에 `IServiceProvider` 가 **없다** (W2-2) |
| 3 | (반제품 언급 없음) | ❌ **P0 누락.** 회계·외상매입금까지 오염 (W2-0 가) |
| 4 | *"`:641` 에 중복 가드가 있다"* | ⚠️ 근거 오지목. 진짜 가드는 `:610-622`+`:626` (결론은 유지) |
| 5 | (`is_auto` 언급 없음) | ❌ 두 경로가 갈린다 (W2-0 나) |
| 6 | *"규모 소~중"* | ❌ **중~대** |

🔴 **교훈**: PM 이 *"있는 걸 잇기만 하면 된다"* 고 판단할 때가 가장 위험하다.
   **잇는 자리의 전제조건**(트랜잭션·DI·업무 타입)을 안 본 채 크기를 말했다.
   ⇒ [[feedback_gate_must_test_behavior]] 와 같은 계통 — **글자를 읽고 동작을 안 봤다.**
🟢 **반증이 안전을 확인해 준 축도 있다**(W2-5) — 창고·draft 전환·원장 길이. **반증은 반대만 하는 게 아니다.**

---

**작성**: 설계팀장 존 · 2026-08-25
**결재 대기**: PM → (SOP [5]) CTO 래리 → 사장님
